# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2690a1e73327af99e5f700e70edfab31d3174d0f196e0309fdcb7cd711750da6ff2c58e407d69d2e4a2742f6228c641470f5f6c84a4e072aadb7be8198f1178d

test:
  secret_key_base: 813b23d59ca02922531c204a9b273cb3fffdeb42cf43b135e63855e8d0e7e4d0cfbbc48f6194b90d8ec62e8c4557076169f8325d29e662a3f358b2085a94396d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
